Repository jenkinsci/active-directory-plugin, pull requests merged in 2020-09, with the labels that each got.

#102 No need to use BeanBuilder or create a custom AbstractUserDetailsAuthenticationProvider
  .mvn/extensions.xml
  .mvn/maven.config
  Jenkinsfile
  pom.xml
  src/main/java/hudson/plugins/active_directory/AbstractActiveDirectoryAuthenticationProvider.java
  src/main/java/hudson/plugins/active_directory/ActiveDirectoryAuthenticationProvider.java
  src/main/java/hudson/plugins/active_directory/ActiveDirectorySecurityRealm.java
  src/main/java/hudson/plugins/active_directory/ActiveDirectoryUnixAuthenticationProvider.java
  src/main/resources/hudson/plugins/active_directory/ActiveDirectory.groovy
  src/test/java/hudson/plugins/active_directory/ActiveDirectoryJCasCCompatibilityTest.java
  src/test/resources/hudson/plugins/active_directory/ActiveDirectorySecurityRealmTest/testReadResolveMultiDomainSingleDomainOneDisplayName.zip
  src/test/resources/hudson/plugins/active_directory/ActiveDirectorySecurityRealmTest/testReadResolveMultiDomainSingleDomainOneDisplayName/config.xml
  src/test/resources/hudson/plugins/active_directory/ActiveDirectorySecurityRealmTest/testReadResolveMultiDomainSingleDomainOneDisplayName/secrets/master.key
  src/test/resources/hudson/plugins/active_directory/ActiveDirectorySecurityRealmTest/testReadResolveMultiDomainTwoDomainsOneDisplayName.zip
  src/test/resources/hudson/plugins/active_directory/ActiveDirectorySecurityRealmTest/testReadResolveMultiDomainTwoDomainsOneDisplayName/config.xml
  src/test/resources/hudson/plugins/active_directory/ActiveDirectorySecurityRealmTest/testReadResolveMultiDomainTwoDomainsOneDisplayName/secrets/master.key
  src/test/resources/hudson/plugins/active_directory/ActiveDirectorySecurityRealmTest/testReadResolveMultipleDomainsOneDomainEndToEnd.zip
  src/test/resources/hudson/plugins/active_directory/ActiveDirectorySecurityRealmTest/testReadResolveMultipleDomainsOneDomainEndToEnd/config.xml
  src/test/resources/hudson/plugins/active_directory/ActiveDirectorySecurityRealmTest/testReadResolveMultipleDomainsOneDomainEndToEnd/secrets/master.key
  src/test/resources/hudson/plugins/active_directory/ActiveDirectorySecurityRealmTest/testReadResolveSingleDomain.zip
  src/test/resources/hudson/plugins/active_directory/ActiveDirectorySecurityRealmTest/testReadResolveSingleDomain/config.xml
  src/test/resources/hudson/plugins/active_directory/ActiveDirectorySecurityRealmTest/testReadResolveSingleDomain/secrets/master.key
  src/test/resources/hudson/plugins/active_directory/ActiveDirectorySecurityRealmTest/testReadResolveSingleDomainSingleServer.zip
  src/test/resources/hudson/plugins/active_directory/ActiveDirectorySecurityRealmTest/testReadResolveSingleDomainSingleServer/config.xml
  src/test/resources/hudson/plugins/active_directory/ActiveDirectorySecurityRealmTest/testReadResolveSingleDomainSingleServer/secrets/master.key
  src/test/resources/hudson/plugins/active_directory/ActiveDirectorySecurityRealmTest/testReadResolveSingleDomainWithTwoServers.zip
  src/test/resources/hudson/plugins/active_directory/ActiveDirectorySecurityRealmTest/testReadResolveSingleDomainWithTwoServers/config.xml
  src/test/resources/hudson/plugins/active_directory/ActiveDirectorySecurityRealmTest/testReadResolveSingleDomainWithTwoServers/secrets/master.key
  src/test/resources/hudson/plugins/active_directory/ActiveDirectorySecurityRealmTest/testReadResolveTwoDomainsWithSpaceAfterComma.zip
  src/test/resources/hudson/plugins/active_directory/ActiveDirectorySecurityRealmTest/testReadResolveTwoDomainsWithSpaceAfterComma/config.xml
  src/test/resources/hudson/plugins/active_directory/ActiveDirectorySecurityRealmTest/testReadResolveTwoDomainsWithSpaceAfterComma/secrets/master.key
  src/test/resources/hudson/plugins/active_directory/ActiveDirectorySecurityRealmTest/testReadResolveTwoDomainsWithSpaceAfterCommaAndSingleServer.zip
  src/test/resources/hudson/plugins/active_directory/ActiveDirectorySecurityRealmTest/testReadResolveTwoDomainsWithSpaceAfterCommaAndSingleServer/config.xml
  src/test/resources/hudson/plugins/active_directory/ActiveDirectorySecurityRealmTest/testReadResolveTwoDomainsWithSpaceAfterCommaAndSingleServer/secrets/master.key
  src/test/resources/hudson/plugins/active_directory/ActiveDirectorySecurityRealmTest/testReadResolveTwoDomainsWithSpaceAfterCommaAndTwoServers.zip
  src/test/resources/hudson/plugins/active_directory/ActiveDirectorySecurityRealmTest/testReadResolveTwoDomainsWithSpaceAfterCommaAndTwoServers/config.xml
  src/test/resources/hudson/plugins/active_directory/ActiveDirectorySecurityRealmTest/testReadResolveTwoDomainsWithSpaceAfterCommaAndTwoServers/secrets/master.key
  src/test/resources/hudson/plugins/active_directory/ActiveDirectorySecurityRealmTest/testReadResolveTwoDomainsWithoutSpaceAfterComma.zip
  src/test/resources/hudson/plugins/active_directory/ActiveDirectorySecurityRealmTest/testReadResolveTwoDomainsWithoutSpaceAfterComma/config.xml
  src/test/resources/hudson/plugins/active_directory/ActiveDirectorySecurityRealmTest/testReadResolveTwoDomainsWithoutSpaceAfterComma/secrets/master.key
  src/test/resources/hudson/plugins/active_directory/ActiveDirectorySecurityRealmTest/testReadResolveTwoDomainsWithoutSpaceAfterCommaAndSingleServer.zip
  src/test/resources/hudson/plugins/active_directory/ActiveDirectorySecurityRealmTest/testReadResolveTwoDomainsWithoutSpaceAfterCommaAndSingleServer/config.xml
  src/test/resources/hudson/plugins/active_directory/ActiveDirectorySecurityRealmTest/testReadResolveTwoDomainsWithoutSpaceAfterCommaAndSingleServer/secrets/master.key
  src/test/resources/hudson/plugins/active_directory/ActiveDirectorySecurityRealmTest/testReadResolveTwoDomainsWithoutSpaceAfterCommaAndTwoServers.zip
  src/test/resources/hudson/plugins/active_directory/ActiveDirectorySecurityRealmTest/testReadResolveTwoDomainsWithoutSpaceAfterCommaAndTwoServers/config.xml
  src/test/resources/hudson/plugins/active_directory/ActiveDirectorySecurityRealmTest/testReadResolveTwoDomainsWithoutSpaceAfterCommaAndTwoServers/secrets/master.key
Labels: removed

#100 Migrate active-directory-plugin documentation from wiki to Github
  CHANGELOG.md
  README.md
  docs/images/ad-domain-controller-configuration.png
  docs/images/ad-internalJenkinsUser.png
  docs/images/ad-managementLink-view.png
  docs/images/ad-multi-domains.png
  docs/images/ad-simple-configuration.png
  docs/images/ad-tls-administrative-monitor.png
  docs/images/ad-tls-selector.png
  pom.xml
Labels: documentation

#103 [JENKINS-63737] Cache AbstractActiveDirectoryAuthenticationProvider
  src/main/java/hudson/plugins/active_directory/ActiveDirectorySecurityRealm.java
  src/test/java/hudson/plugins/active_directory/docker/TheFlintstonesTest.java
Labels: regression
