Repository jenkinsci/active-directory-plugin, pull requests merged in 2024-11, with the labels that each got.

#210 [JENKINS-74035] Extract inline script from `ActiveDirectorySecurityRealm/configAdvanced.jelly`
  src/main/resources/hudson/plugins/active_directory/ActiveDirectorySecurityRealm/ad-turn-off-autocomplete.js
  src/main/resources/hudson/plugins/active_directory/ActiveDirectorySecurityRealm/configAdvanced.jelly
Labels: internal

#211 Remove unused Docker fixtures
  src/test/resources/fixture/Dockerfile
  src/test/resources/fixture/custom-dockerd-entrypoint.sh
  src/test/resources/fixture/daemon.json
Labels: test

#212 Update `Dockerfile` with Dependabot
  .github/dependabot.yml
Labels: skip-changelog

#213 Migrate from Dependabot to Renovate
  .github/dependabot.yml
  .github/renovate.json
Labels: skip-changelog

#214 Update `Dockerfile` used in tests with Renovate
  .github/renovate.json
Labels: skip-changelog
